# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  - TESTS=lint
  - TESTS=all
  - TESTS=all COMPOSER_PARAMETER=--prefer-lowest

jobs:
  exclude:
    - php: 7.2
      env: TESTS=lint
    - php: 7.3
      env: TESTS=all
    - php: 7.4
      env: TESTS=lint
    - php: nightly
      env: TESTS=lint
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
  - travis_retry pecl install ast
  - travis_retry pecl install igbinary

install:
  - travis_retry composer config -g github-oauth.github.com $GH_TOKEN
  - travis_retry composer update $COMPOSER_PARAMETER

script:
  - if [ "$TESTS" = "all" ]; then composer ci; else php -l src; fi

# allow builds for all branches
branches:
  only:
    - /.*/

# disable shallow cloning
git:
  depth: false

## Cache composer bits
cache:
  directories:
    - $HOME/.composer/cache/files
    - $HOME/.npm
